### PR TITLE
Move to netlify

### PR DESCRIPTION
**Pull request by Sajo8**
Reasons why I'd like to move to netlify I outlined in the discord, I'll copy/paste them here for sake of convenience:

"
Hey guys, I was wondering, could we move to netlify for the docs? (possibly api-docs even).
I see many benefits over Travis CI:
- Easy to setup
- Easy to change
- Free HTTPS
- Easily add new domains
- CI/CD, like travis
- Automatically build PRs
-> let you know if they passed or not
-> give you BUILD PREVIEWS with no configuration
- you can add lots of websites easily
- has a neat CLI tool (netlify dev will build your current dir and upload it to share with others)
- no need to mess around with build commands or secrets or whatever
- can config and use it from anywhere
Everytime I've setup a website with netlify, it's been extremely easy and simple. Far easier than messing around with travis.
It was made for website deployment, and it excels at that. Travis just doesn't do that. A big hit for me is build previews, which are super important and would help catch a lot of problems/bugs
"

Soregums was onboard with the idea, so here we go. This is currently only for the user docs, not the api docs. This shouldn't break any compatiblity with the api docs, as of now. 

1. Delete the environment variables in the turtlecoin-docs config on travis (I can do that later)  
2. Merge this PR  
3. Follow these instructions @RocksteadyTC:

---

1. Login to [Netlify](https://netlify.com). You already have an account there, you might've signed in with your GitHub account  
2. Click on "New Site from Git"  
3. Choose "GitHub". It will authenticate with your GitHub acc, you may have to enter your GitHub password.  
4. Click on "RocksteadyTC" and click "TurtleCoin".  
5. Look for turtlecoin-docs in the search bar, and click on it
8. Click "Deploy Site"
9. Click "Domain Settings"
10. Click "Add Custom Domain"
11. Enter "docs.turtlecoin.lol"
12. Click "Yes, add owner"
13. Scroll up the top of the page, and click on the 3 dots next to "Check DNS configuration"
14. Click "Set up Netlify DNS"
15. Click "Verify"
16. Click "Yes, add domain"
17. Click "Continue"
18. Now go to your DNS manager (I believe it's Namecheap) and add the DNS records given. I don't know any exacts so I can't help you out with this one but I know you can do it
19. After adding the DNS records, go back to Netlify and click "Done".
20. Disable github-pages for this repository

That should be it! Auto builds on commits, makes previews on PRs, custom domain, and free HTTPS

/e: Optionally, add zpalm, me, soregums, etc as contributors so that we can manage and trigger deploys and such. At the very least, provide the deploy link so that we can see logs if something isn't working

### CODE REVIEW

**Comment by zpalmtree** [comment]
If there not something like `.netflifyrc` so you can store the build commands in the repo? If not, maybe make a 3 line bash script and execute that instead?

**Comment by Sajo8** [comment]
You can add a [`netlify.toml`](https://www.netlify.com/docs/netlify-toml-reference/) file. Why do you ask?

**Comment by zpalmtree** [comment]
Because I prefer storing build commands in the repo

**Comment by Sajo8** [comment]
Okay, I'll look into it in a bit

**Comment by Sajo8** [comment]
Okay that should work

**Comment by RocksteadyTC** [comment]
ok im at the office, lemme get started

**Comment by RocksteadyTC** [comment]
Add the domain to Netlify
You must own turtlecoin.lol to complete all the steps.

Another site is already using this domain

Domains must be unique across Netlify. Currently another site is using this domain. If you don’t know which site, please contact support for guidance.

**Comment by RocksteadyTC** [comment]
stuck on step 12

**Pull request merged**
