### PR TITLE
Update Using-Zedwallet.md

### PR DESCRIPTION
**Pull request by atomsett**
Update most of the page; changes to binary distribution filenames, zedwallet commands and output, some rewording for clarification and presentation

### CODE REVIEW

**Comment by zpalmtree** [comment]
Great work! Few comments -

* People kept getting confused on the capitalization of the name, so I decided to call it "zedwallet" (all lower case) everywhere.
* Was there a reason to remove the section linking to the remote node guide? Or did it move somewhere else and I missed it?
* I would suggest illustrating the example with the full command name, rather than the numeric access - The main reason being that, if a new command is added, it can potentially change the ordering of all the other commands, so '16' is no longer optimize for example, and secondly, I just think it's a bit easier to remember if you're looking at the guide for a quick reference, a command name that means something, rather than a random number, which is easy to forget.

**Comment by atomsett** [comment]
-:eyes:, but proper nouns for documentation headings?
-Yes the link to remote nodes is now under under 'synchronizing the blockchain', where disk space requirements are mentioned.
-OK although I think this guide will be read 2x or 3x times when someone first uses zedwallet, then never again as all the commands are clearly on screen.

**Comment by zpalmtree** [comment]
* I would say the convention is to use the name of the command as it is invoked, for example https://en.wikipedia.org/wiki/Grep - Aside from the URL, every mention is in lower case.

* OK

* True, I don't think a guide is especially needed if your software is well done - still a good idea to make the docs as clear as possible for those less technically inclined users :grimacing:

**Comment by atomsett** [comment]
- OK and here's the [official website](https://www.gnu.org/software/grep/)
- I've removed spurious Zedwallet reference *except* for the page title, and then it also fits in with the other headings visible on that page in the wiki and the URL.  
- All commands are now written
:-D

**Pull request merged**
