### PR TITLE
Implement API Docs in Docusaurus

### LINKED ISSUE #173: Previews of auto-builds for docs
Example: for sajodocs, i can click on the little green checkmark [here](https://github.com/turtlecoin/sajodocs/pull/8) and be transported to a preview build of the website with the pr merged when a pr is made in the sajodocs repo

Currently there is no such thing for api-docs and thus it's harder to check

Is there anyway this can be fixed/changed?

cc @ar-x

### PR DESCRIPTION
**Pull request by Sajo8**
Looks great, one central source, everything on netlify, resolves #173, looks uniform, and performs faster and smoother than current api-docs. Also less bugs, and easier to modify later on.

It can be merged whenever

### CODE REVIEW

**Comment by Sajo8** [comment]
Preview: https://deploy-preview-283--its-sayjoe.netlify.com/developer/resources

Guides under "API Documentation"

**Comment by Sajo8** [comment]
When merged, could the existing api-docs.turtlecoin.lol website be taken down? @RocksteadyTC and could you make that url instead redirect to https://docs.turtlecoin.lol/developer/resources

**Comment by brandonlehmann** [comment]
The preview you posted still points at api-docs ?

**Comment by SoreGums** [comment]
maybe update the links at the top of the resources page to go internal then?

also it is confusing that this is called Wallet RPC API probably need to call it Legacy Wallet RPC API
i'd put the Daemon JSON RPC first
```
API Documentation
 - Daemon JSON RPC API > links to page
 - Daemon HTTP RPC API > links to page
 - Wallet REST API > https://turtlecoin.github.io/wallet-api-docs/
 - Legacy Wallet API > links to page
```
looks good :t_ok:

**Comment by Sajo8** [comment]
@brandonlehmann  Were you looking at the [wrong link perhaps?](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

The docs are [here](https://deploy-preview-283--its-sayjoe.netlify.com/developer/resources)

The link I posted in the comment mentioning rock is for _after_ this PR is merged, after the URL https://docs.turtlecoin.lol/developer/resources has the API documentation in it.

**Comment by Sajo8** [comment]
Updated it :+1: @SoreGums   
It doesn't let me link directly to an external link from the sidebar so I settled for a page which only contains a link to the documentation for wallet-api

**Comment by brandonlehmann** [comment]
> Updated it 👍 @SoreGums
> It doesn't let me link directly to an external link from the sidebar so I settled for a page which only contains a link to the documentation for wallet-api

Clicked https://deploy-preview-283--its-sayjoe.netlify.com/developer/resources per your 2nd comment here.

Now I'm getting page not found errors on the links via https://deploy-preview-283--its-sayjoe.netlify.com/developer/resources (https://deploy-preview-283--its-sayjoe.netlify.com/developer/api/Daemon-JSON-RPC-API && https://deploy-preview-283--its-sayjoe.netlify.com/developer/api/Legacy-Wallet-RPC-API)

**Comment by Sajo8** [comment]
@brandonlehmann Check now

**Pull request merged**
