### PR TITLE
Revert "Remove info linking to exchanges"

### PR DESCRIPTION
**Pull request by Sajo8**
Reverts turtlecoin/turtlecoin-docs#288

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Denied.

**Comment by Sajo8** [comment]
I disagree;

**Comment by Sajo8** [comment]
I disagree; we should, in the TurtleCoin docs of all places - docs for _everything_ TurtleCoin - let it be known that one can buy TurtleCoin. Wording can, instead, be changed to something like "be bought at places, including <name of one exchange here>, among others". This gives a user a link to an exchange, while also saying that there are more out there where you can buy them.

Removing it all together is childish; the ban on market talk in chat should NOT extend everywhere else.

**Comment by RocksteadyTC** [comment]
We are not sellers of TurtleCoin, and anybody with the skills to buy something has the skills to find it. The buying section does not need to exist. Linking to exchanges, naming exchanges, linking to sources to find more exchanges is part of this ethical conflict.

Commenting on what is childish is outside of the scope of this repository and outside of your role as a maintainer.

**Comment by Sajo8** [comment]
What's the "ethical conflict"? The point of the docs is to make it available. I'm sure plenty of people don't need a step-by-step guide on how to use a web wallet, but it exists anyways. Why? So that it's available and can be referenced to. I don't see how this is any different

**Comment by SoreGums** [comment]
now that rock has said that ^ - disregard my comment in the other one.

+1 remove all buy no-market-talk conflicts

google exists - use it :)

**Comment by RocksteadyTC** [comment]
That is a false equivalence, there is no laws against using webwallets, however, telling our users to buy TurtleCoin falls into an ethical place where we can't be. If you'd like to PR that as a non-maintainer, you're more than welcome to, but TRTL team will not be promoting this in our materials.

**Comment by Sajo8** [comment]
Telling one that they can buy TRTL is an ethical dilemma? I don't see how so. They can buy TRTL, and we tell them it's possible. We don't say you should, or that it's a good idea. We don't recommend it. We just say you _can_

> there is no laws against using webwallets
and there some against buying TRTL?

**Comment by Sajo8** [comment]
> google exists - use it :)

In that case, I don't see a use for guides we have for topics like XMR-Stak, or XMRIg. Plenty of guides exist. Why should we bother making our own if they already exist?

**Comment by brandonlehmann** [comment]
In some jurisdictions it is illegal to have any cryptocurrency whatsoever.

**Comment by Sajo8** [comment]
Let's remove the mining guide then

**Comment by ExtraHash** [comment]
I thought that the "no market talk" rule was strictly for the discord? We clearly don't have that rule here on GitHub, I don't see why it should apply to the website either. Won't this just encourage more people to end up going to the discord and asking?

**Comment by brandonlehmann** [comment]
Read the convo in dev_docs please. The stance is clear.

**Comment by ExtraHash** [comment]
not even the entire core dev team is in agreement about this, the stance is not clear by any means

**Comment by brandonlehmann** [comment]
https://www.sec.gov/news/public-statement/statement-clayton-2017-12-11 Read it. Learn it. Understand it.

**Comment by ExtraHash** [comment]
I fail to see how a public statement regarding ICOs applies whatsoever to TurtleCoin, as we've done no ICO

**Comment by brandonlehmann** [comment]
You didn’t read it. Please stop making a fool of yourself.

**Comment by ExtraHash** [comment]
Which part of this document details that it's illegal to list active markets on a website?

**Comment by ExtraHash** [comment]
ibmcd pointed out this passage in discord

```
Tokens and offerings that incorporate features and marketing efforts that emphasize the potential for profits based on the entrepreneurial or managerial efforts of others continue to contain the hallmarks of a security under U.S. law.
```

which i concede could at least have a fairly decent chance of applying here, so i'll agree that this is probably the right move

**Pull request merged**
