### PR TITLE
Adding Termux mining Guide

### PR DESCRIPTION
**Pull request by afterconnery**
Wrote up a guide to mine on android devices using Termux.

### CODE REVIEW

**Comment by Sajo8** [comment]
this should be three apps: https://i.imgur.com/k4CrxNv.png

Maybe add seperate headings for setting up the miner (installing termux, downloading xmring) and configuring the miner, similar to how it is in the [tony monero](https://github.com/turtlecoin/turtlecoin-docs/blob/master/guides/mining/mobile-mining/Using-Tony-Monero.md) guide?

**Comment by afterconnery** [comment]
That would be good. More detail never hurt anyone.

**Comment by SoreGums** [comment]
nice one :)

**Comment by SoreGums** [comment]
I like the guide as is - you can make more changes if you want

**Pull request merged**
