### PR TITLE
Update XMR-Stak-Guide.md

### PR DESCRIPTION
**Pull request by pstarSR**
"Low_power" mode explanation was wrong. adjusted. 

added New gpu tweaking section for AmdMemoryTweaker program, and settings tutorial for turtle.

### CODE REVIEW

**Comment by pstarSR** [comment]
> Please proofread the Memory Tweaker section and fix stuff like typos and casing. Thank you!

I adjusted the casing a bit for some comments. but Im sorry im not seeing the typos

**Comment by Sajo8** [comment]
No problem, I'll make a few tweaks to your branch in a bit to address them

**Comment by pstarSR** [comment]
> No problem, I'll make a few tweaks to your branch in a bit to address them

please let me know how to address them though so I can get better at this. I feel as though the format was correct. so if it wasnt, I would like to know

**Comment by Sajo8** [comment]
@pstarSR See the above commit I made (bd36e80fa54e64b922a5b8a7206d9018a7b68eb8) to see what I mean

**Comment by pstarSR** [comment]
> Question: Who is the speaker in this text?
> 
> The only reason I ask is the use of “My” on L272 (it may exist in other places). I’m probably being overcritical in my thoughts that while the information is good to know, that the information in core docs should largely be based in concrete facts. Perhaps, reviewing the help information for the miner package and it’s tweaking guides, a more concrete understanding of the low power mode can be relayed to the reader versus presenting an impression of what what it does.

I am speaking in this text, everything written is personal experience and research. I have read the miner docs, it does not "specifically" explain what changing those settings do. I have discussed this with others and its been a back and forth between two ideas of thought about it. We could remove it completely, and just talk about the setting.

I guess that would be the safest bet for that statement. I will change it

**Comment by pstarSR** [comment]
> @pstarSR See the above commit I made ([bd36e80](https://github.com/turtlecoin/turtlecoin-docs/commit/bd36e80fa54e64b922a5b8a7206d9018a7b68eb8)) to see what I mean

yeah I saw, a lot of those are sentence structure and personal preference on how it sounds and looks. I will try to adhere better to your style. Also somethings you are changing are not correct though, you did it with the processor before. you changed my ( false-5) statement to (false - 5+) 5+ doesnt exist. 5 is the last known setting for "low_power". So instead of confusing people with gramatics, I use the setting they would enter. otherwise someone could read that as 5+ is a setting to enter.

**Comment by pstarSR** [comment]
thanks guys for all the help

**Comment by Sajo8** [comment]
> yeah I saw, a lot of those are sentence structure and personal preference on how it sounds and looks. I will try to adhere better to your style. Also somethings you are changing are not correct though, you did it with the processor before. you changed my ( false-5) statement to (false - 5x) 5x doesnt exist. 5 is the last known setting for "low_power". So instead of confusing people with gramatics, I use the setting they would enter. otherwise someone could read that as 5x is a setting to enter.

My bad, I misinterpreted what that was saying

**Pull request merged**
