### PR TITLE
Add error conditions to Walletd RPC documentation

### PR DESCRIPTION
**Pull request by gracelessdragon**
#145

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
@sorenfidelis great job, what's your username in the discord chat?

**Comment by sorenfidelis** [comment]
oh I forgot that would be confusing, @gracelessdragon

**Comment by SoreGums** [comment]
Are we adding this as is or is it being worked on fully first?

**Comment by gracelessdragon** [comment]
My thought was only to setup the framework so someone with the knowledge can fill in the blanks more easily.

**Comment by ZedPea** [comment]
I'm in the process of filling an amount of these in, shouldn't be too long

**Comment by timmcleod** [comment]
Thanks z

**Comment by ZedPea** [comment]
@gracelessdragon I made a PR to your fork filling out most of the walletd errors. I think if you merge it, it should show up here.

I might take another pass later and fill out the errors I'm not sure on by digging into the code.

**Comment by RocksteadyTC** [comment]
image

**Comment by gracelessdragon** [comment]
Looks like it did. Thanks @ZedPea!

**Comment by SoreGums** [comment]
Shall we merge it now? Any further updates can be PRd

**Comment by ZedPea** [comment]
All good on my end. @gracelessdragon ?

**Comment by ZedPea** [comment]
Lol rock gives no fucks

**Comment by RocksteadyTC** [comment]
not one

**Comment by ZedPea** [comment]
Looks like the formatting is a bit fucked on the api-docs side: https://api-docs.turtlecoin.lol/#walletd-errors

**Comment by RocksteadyTC** [comment]
ar-x is going to have somebody's ass for this 


image

**Comment by Sajo811** [comment]
lol w0t

**Comment by gracelessdragon** [comment]
I actually suspected this after I got to looking at the other .mds, I think I can fix it.

**Comment by Sajo811** [comment]
#173 Example^ this could have been prevented

**Pull request merged**
