### PR TITLE
Update termux guide to use NinjaRig

### PR DESCRIPTION
**Pull request by SoreGums**
NinjaRig is best rig, so use it instead :D

### CODE REVIEW

**Comment by SoreGums** [comment]
ok done :)

**Comment by SoreGums** [comment]
tested on a fresh install of android - one-shot works fine.

**Comment by Sajo8** [comment]
Should it be changed to clone https://github.com/turtlecoin/ninjarig instead?

**Comment by SoreGums** [comment]
I'll check again soon as he's made updates. However as of the time of the last force push it didn't compile.

**Comment by SoreGums** [comment]
2019-09-03 09_49_20-pixelc

still blows up 

am merging upstream changes though

**Comment by SoreGums** [comment]
right all merged and up to date.

pretty sure he's not going to add the fix (he told me to put in) to the main repo as it disables a thing that is being used on purpose (that doesn't affect mining)

**Pull request merged**
