### PR TITLE
Create Timeline

### PR DESCRIPTION
**Pull request by TRTLAlien**
I thought this would be good for people to be able to learn about TurtleCoin in a informative and quick manner.

### CODE REVIEW

**Comment by SoreGums** [comment]
made some changes - feel free to change them back or tweak further.

looks great @TRTLAlien

**Comment by SoreGums** [comment]
so all done? shall i merge this now?

**Comment by TRTLAlien** [comment]
Well you can merge it. I won't say that its done though. It's going to be a continued project for me as I research and add in interesting moments of TurtleCoin.

**Comment by SoreGums** [comment]
nice

**Pull request merged**
